apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: actor-statestore
  namespace: pubsub-mcp
spec:
  type: state.postgresql
  version: v1
  metadata:
    - name: connectionString
      secretKeyRef:
        name: ai-mcp-postgres-connection
        key: connectionString
    - name: actorStateStore
      value: "true"
