apiVersion: v1
kind: Secret
metadata:
  name: ai-mcp-postgres-connection
  namespace: pubsub-mcp
type: Opaque
stringData:
  connectionString: "host=ai-mcp-postgres user=dapr password=dapr port=5432 connect_timeout=10 database=dapr_state"
