apiVersion: v1
kind: Service
metadata:
  name: mcp-srvr
  labels:
    app: mcp-srvr
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: http
  selector:
    app: mcp-srvr
