apiVersion: v1
kind: Service
metadata:
  name: readme-mcp
  labels:
    app: readme-mcp
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: http
  selector:
    app: readme-mcp
