apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dapr-components
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com-personal:stiproot/pubsub-mcp.git
    targetRevision: HEAD
    path: argocd/dapr-components

  destination:
    server: https://kubernetes.default.svc
    namespace: pubsub-mcp

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
