apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-svc
  labels:
    app: ai-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-svc
  template:
    metadata:
      labels:
        app: ai-svc
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "ai-svc"
        dapr.io/app-port: "3003"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
      - name: ai-svc
        image: ai-svc:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 3003
          name: app
          protocol: TCP
        env:
        - name: PORT
          value: "3004"
        - name: NODE_ENV
          value: "production"
        - name: DAPR_HOST
          value: "127.0.0.1"
        - name: DAPR_HTTP_PORT
          value: "3500"
        - name: DAPR_GRPC_PORT
          value: "50001"
        - name: CTX_SVC_URL
          valueFrom:
            configMapKeyRef:
              name: ai-svc-config
              key: CTX_SVC_URL
        - name: NATS_URL
          valueFrom:
            configMapKeyRef:
              name: ai-svc-config
              key: NATS_URL
        - name: PUBSUB_NAME
          valueFrom:
            configMapKeyRef:
              name: ai-svc-config
              key: PUBSUB_NAME
        - name: STATE_STORE_NAME
          valueFrom:
            configMapKeyRef:
              name: ai-svc-config
              key: STATE_STORE_NAME
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 5
